// Wallet
export const BTC_WALLET_GET_BLOCKCHAININFO = 'BTC_WALLET_GET_BLOCKCHAININFO';
export const BTC_CLIENT_STATUS = 'BTC_CLIENT_STATUS';
export const BTC_WALLET_LIST_DATA_SHOW = 'WALLETLIST_DATA_SHOW';
export const BTC_WALLET_DETAILS = 'WALLET_DATA_SHOW';
export const BTC_WALLET_ADDRESS = 'WALLET_ADDRESS';
export const SEND_BITCOIN = 'SEND_BITCOIN';

// Ln
export const LN_WALLET_GET_FUNDS = 'LN_WALLET_GET_FUNDS';
export const LN_WALLET_NODEINFO = 'LN_WALLET_NODEINFO';
export const LN_WALLET_DECODE_BOLT = 'LN_WALLET_DECODE_BOLT';
export const LN_WALLET_GET_ROUTE = 'LN_WALLET_GET_ROUTE';
export const LN_WALLET_PAY_BOLT = 'LN_WALLET_PAY_BOLT';
export const LN_WALLET_CREATE_INVOICE = 'LN_WALLET_CREATE_INVOICE';
export const LN_WALLET_GET_PEERS = 'LN_WALLET_GET_PEERS';
export const LN_WALLET_OPEN_FUND_PEER_CHANNEL =
  'LN_WALLET_OPEN_FUND_PEER_CHANNEL';
export const LN_WALLET_GET_NEW_ADDRESS = 'LN_WALLET_GET_NEW_ADDRESS';
export const LN_WALLET_WITHDRAW_FUNDS = 'LN_WALLET_WITHDRAW_FUNDS';

// Wasabi
export const WASABI_WALLET_GET_UNSPENTCOINS = 'WASABI_WALLET_GET_UNSPENTCOINS';
export const WASABI_WALLET_GET_TXNS = 'WASABI_WALLET_GET_TXNS';
// Auth
export const REQUEST_PAIR = 'REQUEST_PAIR';
export const GET_AUTH_STATUS = 'GET_AUTH_STATUS';
export const AUTH_INFO_STATUS = 'AUTH_INFO_STATUS';
export const PGP_GET_KEYS = 'GET_PGP_KEYS';
export const PGP_UNLOCK_KEYS = 'PGP_UNLOCK_KEYS';

export const GET_TOKEN_FROM_QR = 'GET_TOKEN_FROM_QR';
export const MATRIX_CLIENT = 'ACTION_MATRIX_CLIENT';

// Rooms
export const GET_ROOMS_LIST = 'GET_ROOMS_LIST';
export const GET_ROOM_MSG = 'GET_ROOM_MSG';
