import {Dimensions} from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;

export default Constants = {
  STR_My_Wallets: 'My Wallets',
  STR_WALLET: 'WALLET',
  STR_CHAT: 'CHAT',
  STR_SHOP: 'SHOP',
  SCREEN_WIDTH: Dimensions.get('window').width,
  SCREEN_HEIGHT: Dimensions.get('window').height,
  STR_Cur_Balance: 'Current Balance',
  TRANSACTIONS: 'Transactions',
  STR_SEND: 'SEND',
  STR_Send: 'Send',
  STR_RECEIVE: 'RECEIVE',
  STR_Enter_addr: 'Enter an address',
  SCAN_ORSCAN: 'or scan a QR code',
  STR_Enter_Addr: 'Enter Address',
  STR_CONTINUE: 'CONTINUE',
  STR_PAYMENT_RECEIPIENT: 'PAYMENT RECEIPIENT',
  STR_PAYMENT_AMOUNT: 'PAYMENT AMOUNT',
  STR_BTC: 'BTC',
  STR_CONFIRM: 'CONFIRM',
  STR_DONE: 'DONE',
  STR_PAYMENT: 'PAYMENT',
  STR_SENT: 'SENT',
  STR_RECEIVED: 'RECEIVED',
  STR_FEES: 'FEES',
  STR_SENDER: 'SENDER',
  STR_RECEIPIENT: 'RECEIPIENT',
  STR_Wait: 'Approximate Wait',
  STR_Manage_Fund: 'MANAGE FUNDS',
  STR_SET_FEES: 'SET FEES',
  RECT_DIMENSIONS: SCREEN_WIDTH * 0.65,
  RECT_BORDER_WIDTH: SCREEN_WIDTH * 0.005,
  SCAN_BAR_WIDTH: SCREEN_WIDTH * 0.46,
  SCAN_BAR_HEIGHT: SCREEN_WIDTH * 0.0025,
  OVERLAY_COLOR: 'rgba(0,0,0,0.5)',
  SCAN_BAR_COLOR: '#22ff00',
  STR_SHARE: 'SHARE',
  STR_YOU: 'YOU',
  STR_WATCH_ADDR: 'Watch this address',
};
